### ISSUE TITLE
Organization logo

### ISSUE THREAD

**Issue by andreoav** [artesaos/art#1]
Please vote using [zenhub.io](http://zenhub.io) +1 feature.

**Comment by andreoav** [comment]
![artesaos1](https://cloud.githubusercontent.com/assets/508827/6399441/43644444-bdd1-11e4-85c5-0c58c87a6981.jpg)

**Comment by andreoav** [comment]
![artesaos2](https://cloud.githubusercontent.com/assets/508827/6399443/49adfb42-bdd1-11e4-8828-e3077f2da95c.jpg)

**Comment by andreoav** [comment]
![artesaos3](https://cloud.githubusercontent.com/assets/508827/6399446/4e291544-bdd1-11e4-9b48-1aed7bb19d4e.jpg)

**Comment by andreoav** [comment]
![logo2](https://cloud.githubusercontent.com/assets/508827/6399451/5227d112-bdd1-11e4-8c91-825366dec2b7.png)

**Comment by andreoav** [comment]
![logo4](https://cloud.githubusercontent.com/assets/508827/6399454/560683b4-bdd1-11e4-9907-8ca89f27ce02.png)

**Comment by andreoav** [comment]
![logo7](https://cloud.githubusercontent.com/assets/508827/6399461/5d25e734-bdd1-11e4-835c-2643ce08f916.png)

**Comment by andreoav** [comment]
![logo8](https://cloud.githubusercontent.com/assets/508827/6399470/627ee528-bdd1-11e4-99fe-e70d11c9d2c3.png)

**Comment by julihermes** [comment]
Primeira Imagem! +1

**Comment by KILLME56k** [comment]
Primeira!!!

**Comment by Rigolon** [comment]
Segue as sugestões que tinha criado:

01-01:
![demo-03](https://cloud.githubusercontent.com/assets/2759081/6401598/65780502-bde0-11e4-8f1d-779bd150ccd8.png)

01-02:
![demo-02](https://cloud.githubusercontent.com/assets/2759081/6401599/657966d6-bde0-11e4-831b-4721d0324eaa.png)

01-03:
![demo-01](https://cloud.githubusercontent.com/assets/2759081/6401600/657b6878-bde0-11e4-9c76-9c02eee9220d.png)

**Comment by Fuhrmann** [comment]
Primeira mas sem o "artesãos".

**Comment by angelorubin** [comment]
Primeira Imagem +1

**Comment by SOSTheBlack** [comment]
01-01

**Comment by ramon-villain** [comment]
:+1:  1

**Comment by enieber** [comment]
1

**Comment by ghost** [comment]
1

**Comment by andreoav** [comment]
@Fuhrmann o logo que vencer vai ter a versão com a palavra e a versão só com a arte.

**Comment by Fuhrmann** [comment]
@andreoav Tranquilo. Foi o que eu imaginei! Valeu!

**Comment by rafaelign** [comment]
1
